### ISSUE TITLE
NATS implementation

### ISSUE THREAD

**Issue by juicemia** [src-d/go-queue#17]
I've got some code for connecting to NATS littered around in a bunch of places. I was going to write a library like `database/sql` to abstract it away, but I figured somebody would have beaten me to it.

Is a PR for a NATS implementation something you'd merge? Or is that outside of the scope of this?

**Comment by juicemia** [comment]
That sounds good actually. Thank you.

**Comment by jfontan** [comment]
I'm closing this but ping me if you have questions or you create the library to link it from readme.
